name: Dotnet Test Build

on: [push]

jobs:
  build-rmbox:
    name: Build Binary

    strategy:
      matrix:
        target:
        - '{"rid":"win-x64","os":"windows-latest","proj":"rmbox"}'
        - '{"rid":"osx-x64","os":"macos-latest","proj":"rmbox"}'
        - '{"rid":"win-x64","os":"windows-latest","proj":"rmbox-shell"}'
        - '{"rid":"osx-x64","os":"macos-latest","proj":"rmbox-shell"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Build and Pack
      run: dotnet publish src/${{ fromJson(matrix.target).proj }}/ --configuration Release /bl:binlog/${{ fromJson(matrix.target).proj }}-${{ fromJson(matrix.target).os }}.binlog

    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ fromJson(matrix.target).proj }}-${{ fromJson(matrix.target).os }}
        path: binlog/${{ fromJson(matrix.target).proj }}-${{ fromJson(matrix.target).os }}.binlog
