name: Build

on: [push, pull_request]

jobs:
  publish:
    name: Build Binary
    
    strategy:
      matrix:
        target:
        - '{"rid":"win-x64","os":"windows-latest"}'
        - '{"rid":"linux-x64","os":"ubuntu-latest"}'
        - '{"rid":"osx-x64","os":"macos-latest"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build and Pack
      run: ./build.cmd Full --configuration Release --runtime ${{ fromJson(matrix.target).rid }}
    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rmbox-${{ fromJson(matrix.target).rid }}-${{ github.sha }}
        path: dist/rmbox.7z
